module.exports = {
  ERRORS: {
    zacNotFound: "No Zac Found",
    verifiedAlready: "Verified already",
    userCompany: "User company not found",
    resourceNotFound: "Resource not found!",
    meanBookingNotFound: "Mean Booking not found!",
    unverifiedEmail: "Kindly verify your email first!",
    adminExistsForCompany: "Admin exists for this company!",
    siteNameExists: "Site with this name exists!",
    deleteAdminFirst: "Delete it's admin first",
    deleteSiteFirst: "Delete it's sites first",
    deleteClientAdminSitesFirst: "Delete it's admin's sites first",

    picNotFound: "Pic not found",
    siteNotFound: "No Site Found",
    clientNotActive: "Client not active",

    incidentDateBeforeSiteStartDate:
      "Incident Date Cannot Be Before Site's Start Date ",

    incidentDateBeforeSiteEndtDate:
      "Incident Date Cannot Be After Site's End Date ",

    meanStartDateBeforeSiteStartDate:
      "Mean Start Date Cannot Be Before Site's Start Date ",

    meanStartDateBeforeSiteEndtDate:
      "Mean End ate Date Cannot Be After Site's End Date ",

    meanEndDateBeforeSiteStartDate:
      "Mean End Date Cannot Be Before Site's Start Date",
    meanEndDateAfterSiteEndtDate:
      "Mean End Date Cannot Be After Site's End Date",

    tradeNotFount: "No Trade Found",
    organigrammeNotFound: "No Organigramme Found",
    adminNotFound: "No Admin Found",

    levelNotFound: "No Level Found",
    levelExists: "Level Already Exists",

    userAlreadyExists: "User exists",

    clientNotFound: "No Client Found",

    userSitesNotFound: "No Site Found",

    invoiceNotFound: "No Invoice Found",

    zacAlreadyExists: "Zac already exists",

    error: "There was an error!",
    nameRequired: "Name Is Required",
    typeRequired: "Type Is Required",
    emailRequired: "Email is required",
    imageRequired: "Image is required",
    emailExists: "Email already exists",
    userNotFound: "User does not exist",
    meanNotFound: "Mean Does Not Exist",
    companyNotFound: "No Company Found",
    locationNotFound: "No Location Found",
    buildingNotFound: "No Building Found",
    contractNotFound: "No Contract Found",
    userIdRequired: "User ID Is Required",
    userIdRequired: "User ID Is Required",
    deliveryNotFound: "Delivery Not Found",
    phoneLength: "Phone must be 10 digits",
    alreadySubscribed: "Already Subscribed",
    locationRequired: "Location Is Required",
    startDateRequired: "Start Date Required",
    passwordRequired: "Password is required",
    passwordRequired: "Password is required",
    levelNameRequired: "Level Name Required",
    userRoleRequired: "User Role Is Required",
    passwordInvalid: "Password is incorrect!",
    endDateIsRequired: "End Date Is Requried",
    userRoleRequired: "User Role Is Required",
    passwordInvalid: "Password is incorrect!",
    buildingIdRequired: "Building Id Required",
    recipientRequired: "Recipient is required",
    subscriptionExpired: "Subscription Expired",
    sitePenaltyNotFound: "No Site Panelty Found",
    storageAreaNotFount: "No Storage Area Found",
    storageAreaAlreadyAssign: "Storage Area is already assign",
    oldPasswordInvalid: "Old Password is incorrect!",
    storageAreaRequestNotFound: "No Storage Area Request Found",

    siteCompanyNotFound: "No Site Company Found",
    startDateIsRequred: "Start Date Is Requried",
    userNameExists: "Username is not available!",
    alreadyVerified: "Email is already verified",
    siteIncidentsNotFound: "Incidents Not Found",
    subscriptionNotFound: "No Subscription Found",
    indcidentNotFound: "Indcident Does Not Exist",
    deliveyAreaNotFount: "No Delivery Area Found",
    userAddedToSite: "User Already Added To Site.",
    companyAlreadyExists: "Company Already Exists",
    emailInvalid: "No user found with that Email!",
    companyTradeNotFound: "No Company Trade Found",
    leveRequired: "Please Select A Building Level",
    companyLogoRequired: "Company Logo Is Requried",
    companyLogoRequired: "Company Logo Is Requried",
    notAuthorized: "Not authorized for this route!",
    locationTypeRequired: "Location Type Is Required",
    clientRequestNotFound: "Client Request Not Found",
    parentCompanyNotFound: "No Incubent Company Selected",
    invalidToken: "Invalid or expired password reset token",
    endDateCannotBeFromPast: "End Date Cannot Be From Past",
    companyInchargeIsRequired: "Company Incharge Is Required",
    subscriptionPending: "Your Subscription Request Is Pending.",
    startDateCannotBeFromPast: "Start Date Cannot Be From The Past",
    buildingNameAlreadyExists: "This building name already exists.",
    invalidCompanyTradeAssign: "Only Company's trade can be assigned.",
    startDateShoudBeBeforeEndDate: "Start Date Should Be Before End Date",
    endDateShouldBeAfeterStartDate: "End Date Should Be After Start Date",
    inactiveAccount: "Your account is not active! Kindly contact support!",
    delteSiteFirst: "You need to delete user sites before deleting the user",
    locationAddressRequired: "Location Address Reuired For Exterior Location",
    locationBuildingRequired: "Location Building Reuired For Interior Location",
    roleOfCompanyAlreadyExist: "Role of company already exist",
    userAlreadyExistWithAdminRole: "User Already Exist with Admin Role",
    requestedDateIsNotBetweenStorageAreaDate:
      "Requested date is not between storage area date",
    companyDataValidation:
      "Company Name and Type (Enterprise mandataire, Sous-traitant) are Mandatory",
    fileNotFound: "file not Found",
    downloadcsvFile: "File download successFully",
  },
  TEXTS: {
    allUsers: "All users",
    userData: "User data",
    userAdded: "User Added",
    userCreated: "User created",
    userUpdated: "User updated",
    userDeleted: "User deleted",
    quoteCreated: "Quote Created",
    userCompany: "User company requested",

    picCreated: "Pic created",
    picUpdated: "Pic updated",
    picDeleted: "Pic deleted",
    picRequested: "Pic Requested",

    picCreated: "Pic created",
    picUpdated: "Pic updated",
    picDeleted: "Pic deleted",
    picRequested: "Pic Requested",

    clientCreated: "Client created",
    clientUpdated: "Client deleted",
    clientDeleted: "Client deleted",
    clientVerified: "Client verified",
    clientRequested: "Client requested",
    clientsRequested: "Clients requested",
    clientExistsAlready: "Client exists already",

    invoiceCreated: "Invoice created",
    invoiceUpdated: "Invoice deleted",
    invoiceDeleted: "Invoice deleted",
    invoiceRequested: "Invoice requested",
    invoicesRequested: "Invoices requested",
    invoiceExistsAlready: "Invoice exists already",

    adminCreated: "Admin created",
    adminUpdated: "Admin updated",
    adminDeleted: "Admin deleted",
    adminRequested: "Admin requested",
    adminsRequested: "Admins requested",
    adminExistsAlready: "Admin exists already",

    companyData: "Company data",
    companyAdded: "Company Added",
    addCompaniesData: "Companies Data",
    CompaniesUserData: "Companies User Data",
    companyCreated: "Company created",
    companyUpdated: "Company updated",
    companyDeleted: "Company deleted",
    companyRequested: "Company requested",
    companysRequested: "Companys requested",
    companyExistsAlready: "Company exists already",

    deliveryData: "Delivery Data",
    allDeliveries: "All Deliveries",
    deliveryAdded: "Delivery Added",
    deliveryCreated: "Delivery Created",
    deliveryUpdated: "Delivery Updated",
    deliveryDeleted: "Delivery Deleted",
    deliveryRequested: "Delivery Requested",

    companyTradesData: "Company Trades",
    allCompanyTrades: "All Company Trades",
    companyTradeAdded: "Company Trade Added",
    companyTradeCreated: "Company Trade Created",
    companyTradeUpdated: "Company Trade Updated",
    companyTradeDeleted: "Company Trade Deleted",
    companyTradeRequested: "Company Trade Requested",

    buildingCreated: "Building Created",
    historyCreated: "History Created",
    getHistory: "Get History Successfully",

    buildingDeleted: "Building Deleted",
    buildingUpdated: "Building Updated",
    buildingRequested: "Building Requested",

    contractCreated: "Contract Created",
    contractDeleted: "Contract Deleted",
    contractUpdated: "Contract Updated",
    contractRequested: "Contract Requested",

    levelCreated: "Level Created",
    levelDeleted: "Level Deleted",
    levelUpdated: "Level Updated",
    levelRequested: "Level Requested",

    allDeliveryAreas: "All Delivery Areas",
    deliveryAreaCreated: "Delivery Area Created",
    deliveryAreaDeleted: "Delivery Area Deleted",
    deliveryAreaUpdated: "Delivery Area Updated",
    deliveryAreaRequested: "Delivery Area Requested",
    getDeliveryAllStorageArea: "get Delivery All StorageArea",
    getValidatedDeliveryMean: "get Validated Delivery Mean",

    allStorateAreas: "All Storage Areas",
    storateAreaCreated: "Storage Area Created",
    storateAreaDeleted: "Storage Area Deleted",
    storateAreaUpdated: "Storage Area Updated",
    storateAreaRequested: "Storage Area Requested",

    storateAreaRequestCreated: "Storage Area Request Created",
    storateAreaRequestDeleted: "Storage Area Request Deleted",
    storateAreaRequestAccepted: "Storage Area Request Accepted",
    storateAreaRequestRejected: "Storage Area Request Rejected",

    allSiteIncident: "All Incidents",
    siteIncidentsCreated: "Incidents Created",
    siteIncidentsDeleted: "Incidents Deleted",
    siteIncidentsUpdated: "Incidents Updated",
    siteIncidentsRequested: "Incidents Requested",

    zacCreated: "Zac Created",
    zacUpdated: "Zac Updated",
    zacDeleted: "Zac Deleted",
    siteUpdated: "Site Updated",
    siteDeleted: "Site deleted",
    zacRequested: "Zac Requested",
    zacsRequested: "Zacs Requested",
    clientUpdated: "Client Updated",

    allSitePenalties: "All Site Penalty",
    sitePenaltyCreated: "Site Penalty Created",
    sitePenaltyDeleted: "Site Penalty Deleted",
    sitePenaltyUpdated: "Site Penalty Updated",
    sitePenaltyRequested: "Site Penalty Requested",

    allReinvoicing: "All Re-Invoicing",
    reinvoicingCreated: "Re-Invoicing Created",
    reinvoicingDeleted: "Re-Invoicing Deleted",
    reinvoicingUpdated: "Re-Invoicing Updated",
    reinvoicingRequested: "Re-Invoicing Requested",

    tradeDeleted: "Trade Deleted",
    tradeCreated: "Trade Created",
    tradeUpdated: "Trade Updated",
    tradeRequested: "Trade Requested",

    organigrammeDeleted: "Organigramme Deleted",
    organigrammeCreated: "Organigramme Created",
    organigrammeUpdated: "Organigramme Updated",
    organigrammeRequested: "Organigramme Requested",
    allOrganigramme: "All Organigrammes",

    allMeanBookings: "All Mean Bookings",
    FilterBookingCalendar: "Filter Booking Calendar",
    meanBookingDeleted: "Mean Booking Deleted",
    meanBookingCreated: "Mean Booking Created",
    meanBookingUpdated: "Mean Booking Updated",
    meanBookingValidated: "Mean Booking Validated",
    meanBookingRequested: "Mean Booking Requested",

    locationDeleted: "Location Deleted",
    locationCreated: "Location Created",
    locationUpdated: "Location Updated",
    locationRequested: "Location Requested",

    allIncidents: "All Incidents",
    incidentDeleted: "Incident Deleted",
    incidentCreated: "Incident Created",
    incidentUpdated: "Incident Updated",
    incidentRequested: "Incident Requested",

    allZacs: "All Zacs",
    allMeans: "All Means",
    getPath: "Path Get Successfully",

    allLevels: "All Levels",
    allTrades: "All Trades",
    siteCreated: "Site created",
    meanCreated: "Mean Created",
    meadDeleted: "Mean Deleted",
    meanUpdated: "Mean Updated",
    allLocations: "All Locations",
    allContracts: "All Contracts",
    allBuildings: "All Buildings",
    siteArchived: "Site Archived",
    siteUnArchived: "Site Unarchived",
    meanRequested: "Mean Requested",
    siteRequested: "Site Requested",
    sitesRequested: "Site Requested",
    clientDeleted: "Client deleted",
    userSitesUpdated: "Site Updated",
    userSitesDeleted: "Site deleted",
    companyUpdated: "Company Updated",
    compantDeleted: "Company deleted",
    userSiteRequested: "Site Requested",
    passwordSuccess: "Password updated",
    clientRequest: "Client Request Sent",
    companyRequested: "Company Requested",
    loginSuccess: "User login successful",
    enterpriseDelivery: "Enterprise Delivery",
    siteCompanyUpdated: "Site Company Updated",
    siteCompanyDeleted: "Site Company deleted",
    subscriptionDeleted: "Subscription deleted",
    subscriptonRequested: "Subscription Request",
    emailVerified: "Email verified successfully",
    requestResetPasswordSubject: "Password reset",
    passwordResetSent: "Password reset link sent",
    siteCompanyRequested: "Site Company Requested",
    completeRegistration: "Registration completed",
    allRequestedSubscriptions: "All Subscriptions",
    requestEmailVerificationSubject: "Verify your email",
    requestEmailSubject: "Email Notification",

    sendSubscriptionActivationConfirmationSubject:
      "Subscription activated successfully",

    success: "Success",
    tokenIsValid: "Token is valid",
    clientUpdated: "Client Updated",
    emailVerificationSent: "Email verfication link sent",
    subscriptionStatusChanged: "Subscription Status Changed",
    sendEmailConfirmationSubject: "Email verified successfully",
    requestSubscriptionActivationSubject: "Confirm your subscription",
    sendPasswordResetConfirmationSubject: "Password was reset successfully",
    notification: "notification",
  },
  QUOTEREDIRECT: "http://localhost:5000/api/v1/client/",
  ROLES: {
    ALL: "ALL",
    USER: "USER",
    ADMIN: "ADMIN",
    BUFFER: "BUFFER",
    TRAFFIC: "TRAFFIC",
    NOADMIN: "NOADMIN",
    SUPERADMIN: "SUPERADMIN",
    ENTERPRISE: "ENTERPRISE",
    MASTERADMIN: "MASTERADMIN",
    ADMINPERSITE: "ADMINPERSITE",
  },
  STATUS: {
    PAID: "PAID",
    ACTIVE: "ACTIVE",
    CLOSED: "CLOSED",
    UNPAID: "UNPAID",
    INSIDE: "INSIDE",
    ALERTE: "ALERTE",
    REFUSE: "REFUSE",
    DELETED: "DELETED",
    PENDING: "PENDING",
    OUTSIDE: "OUTSIDE",
    REJECTED: "REJECTED",
    ARCHIVED: "ARCHIVED",
    APPROVED: "APPROVED",
    MODIFIED: "MODIFIED",
    INACTIVE: "INACTIVE",
    COMPLETED: "COMPLETED",
    SCHEDULED: "SCHEDULED",
    AVAILABLE: "AVAILABLE",
    VALIDATED: "VALIDATED",
    UNAPPROVED: "UNAPPROVED",
    UNAVAILABLE: "UNAVAILABLE",
    UNSCHEDULED: "UNSCHEDULED",
    COMPLETEDWITHISSUE: "COMPLETEDWITHISSUE",
  },
  INVOICETYPES: {
    WAYS: "WAYS",
    DELAY: "DELAY",
    INCIDENT: "INCIDENT",
    UNPLANNEDDELIVERY: "UNPLANNEDDELIVERY",
  },
  LEVELTYPE: {
    BOTH: "BOTH",
    STORAGE: "STORAGE",
    DELIVERY: "DELIVERY",
  },
  LOCATIONTYPE: {
    EXTERIOR: "EXTERIOR",
    INTERIOR: "INTERIOR",
  },
  MEANTYPES: {
    BOTH: "BOTH",
    LIFTING: "LIFTING",
    ROUTING: "ROUTING",
  },
  CONTRACTTYPES: {
    MASTERCLIENT: "MASTERCLIENT",
    CLIENTPERSITE: "CLIENTPERSITE",
  },
  COMPANYTYPE: {
    NOCLIENTS: "NOCLIENTS",
    MASTERCLIENT: "MASTERCLIENT",
    CLIENTPERSITE: "CLIENTPERSITE",
  },
  FUNCTIONALITY: {
    DELIVERY: "DELIVERY",
  },
  INCIDENTTYPE: {
    MEAN: "MEAN",
    DELAY: "DELAY",
    INCIDENT: "INCIDENT",
    LETIGATON: "LETIGATION",
    UNEXPRECTED: "UNEXPRECTED",
  },
  INCIDENTSTATUS: {
    OPEN: "OPEN",
    CLOSED: "CLOSED",
  },
  SITEPENALTY: {
    LATE: "LATE",
    UNEXPRECTED: "UNEXPECTED",
  },
  MEANLOCATIONTYPE: {
    LEVEL: "LEVEL",
    EXTERIOR: "EXTERIOR",
    STORAGEAREA: "STORAGEAREA",
    DELIVERYAREA: "DELIVERYAREA",
  },
  ORGANIGRAMMETYPE: {
    SITE: "SITE",
    LOGISTICS: "LOGISTICS",
  },
  STORAGEAREAREQUESTSTATUS: {
    PENDING: "PENDING",
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
  },
  MODALS: {
    ZAC: "Zac",
    MEAN: "Mean",
    USER: "User",
    SITE: "Site",
    USER: "User",
    ALERT: "Alert",
    LEVEL: "Level",
    TOKEN: "Token",
    TRADES: "Trades",
    CLIENT: "Client",
    COMPANY: "Company",
    INVOICE: "Invoice",
    SITEPIC: "SITEPIC",
    LEVELPIC: "LEVELPIC",
    INCIDENT: "Incident",
    LOCATION: "Location",
    CONTRACT: "Contract",
    BUILDING: "Building",
    HISTORY: "History",

    DELIVERY: "Delivery",
    MATERIAL: "Material",
    VECHICLES: "Vehicles",
    USERSITES: "UserSites",
    MEANBOOKING: "MeanBooking",
    STORAGEAREA: "StorageArea",
    ORGANIGRAMME: "ORGANIGRAMME",
    DELIVERYAREA: "DeliveryArea",
    SUBSCRIPTION: "Subscription",
    CLIENTINVOICE: "ClientInvoice",
    COMPANYTRADES: "CompanyTrades",
    SITEPENALTIES: "SitePenalties",
    SITECOMPANIES: "SiteCompanies",
    SITEINCIDENTS: "SITEINCIDENTS",
    STORAGEAREAREQUEST: "StorageAreaRequest",
  },
  FORMATS: {
    DATE: "DD-MM-YYYY hh:mm",
  },
};
